server:
  port: 8000
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id : user-service
        uri: lb://user-service
        predicates:
        - Path=/users/**
      - id : inventory-service
        uri: lb://inventory-service
        predicates:
        - Path=/inventory/**
      - id : order-service
        uri: lb://order-service
        predicates:
        - Path=/orders/**
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost}:9411/api/v2/spans