server:
  port: 8001
spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/userdbDev
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
     ddl-auto: update
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost}:9411/api/v2/spans