server:
  port: 8003
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    url: jdbc:postgresql://${DB_SERVER:localhost}:5432/ecommdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
     ddl-auto: update
  kafka:
    producer:
      bootstrap-servers:
      - ${KAFKA_SERVER:localhost}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      bootstrap-servers:
      - ${KAFKA_SERVER:localhost}:9092
      group-id: ordersgroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.orderservice.dto.OrderResponseDTO
            use:
              type:
                headers: false
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost}:9411/api/v2/spans