server:
  port: 8002
spring:
  application:
    name: INVENTORY-SERVICE
  profiles:
    active: dev   
  config:
    import:
    - configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  tracing:
    sampling:
      probability: 1.0