server:
  port: 8002
spring:
  application:
    name: INVENTORY-SERVICE
  profiles:
    active: dev   
  config:
    import:
    - configserver:${CONFIG_SERVER:http://localhost}:8888
  kafka:
    producer:
      bootstrap-servers:
      - ${KAFKA_SERVER:localhost}:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ordersgroup
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.inventoryservice.dto.OrderResponseDTO
            use:
              type:
                headers: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost}:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost}:9411/api/v2/spans