server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: ${git.uri}
          password: ${git.password}
          username: ${git.username}
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER:http://localhost}:8761/eureka/
          